import Foundation

/// Comprehensive anomaly detection report generated by `RansomwareAnomalyGuard`.
public struct RansomwareAnomalyReport: Sendable, Equatable {
    /// Indicates whether a critical ransomware pattern or abnormal rate of change was detected.
    public let isAnomalyDetected: Bool
    /// Fraction of files changed (modified + deleted) relative to total source files (0.0 .. 1.0).
    public let modifiedRatio: Double
    /// Count of modified files in the diff.
    public let modifiedCount: Int
    /// Count of deleted files in the diff.
    public let deletedCount: Int
    /// Total source files evaluated.
    public let totalSourceFiles: Int
    /// Relative paths of files matching known ransomware extensions.
    public let suspiciousExtensionFiles: [String]
    /// Human-readable explanation of why the anomaly was triggered.
    public let reason: String?

    public init(
        isAnomalyDetected: Bool,
        modifiedRatio: Double,
        modifiedCount: Int,
        deletedCount: Int,
        totalSourceFiles: Int,
        suspiciousExtensionFiles: [String] = [],
        reason: String? = nil
    ) {
        self.isAnomalyDetected = isAnomalyDetected
        self.modifiedRatio = modifiedRatio
        self.modifiedCount = modifiedCount
        self.deletedCount = deletedCount
        self.totalSourceFiles = totalSourceFiles
        self.suspiciousExtensionFiles = suspiciousExtensionFiles
        self.reason = reason
    }
}

/// Proactive security shield analyzing change rates and ransomware signatures before committing snapshots.
public struct RansomwareAnomalyGuard: Sendable {
    /// Known ransomware extension signatures commonly appended to encrypted files.
    public static let knownSuspiciousExtensions: Set<String> = [
        ".locked", ".crypto", ".crypted", ".enc", ".wncry", ".locky",
        ".cerber", ".wannacry", ".darkside", ".ryuk", ".revil",
        ".conti", ".blackcat", ".lockbit", ".stop", ".djvu",
        ".phobos", ".dharma", ".makop"
    ]

    /// Evaluates rate-of-change metrics and suspicious extensions for a completed scan and diff analysis.
    /// - Parameters:
    ///   - totalFiles: Total count of files in the source dataset.
    ///   - modifiedCount: Count of modified files detected.
    ///   - deletedCount: Count of deleted files detected.
    ///   - candidatePaths: List of relative paths (e.g. added and modified files) to check for suspicious extensions.
    ///   - enableGuard: Master toggle for anomaly guard.
    ///   - maxChangeThresholdPercent: Maximum allowed percentage change (e.g. 20.0 for 20%).
    ///   - maxDeletedThresholdCount: Maximum allowed absolute deleted count (e.g. 200).
    ///   - detectSuspiciousExtensions: Whether to inspect file extensions for ransomware patterns.
    /// - Returns: A detailed `RansomwareAnomalyReport`.
    public static func evaluate(
        totalFiles: Int,
        modifiedCount: Int,
        deletedCount: Int,
        candidatePaths: [String],
        enableGuard: Bool = true,
        maxChangeThresholdPercent: Double = 20.0,
        maxDeletedThresholdCount: Int = 200,
        detectSuspiciousExtensions: Bool = true
    ) -> RansomwareAnomalyReport {
        guard enableGuard else {
            return RansomwareAnomalyReport(
                isAnomalyDetected: false,
                modifiedRatio: 0,
                modifiedCount: modifiedCount,
                deletedCount: deletedCount,
                totalSourceFiles: totalFiles,
                suspiciousExtensionFiles: [],
                reason: nil
            )
        }

        let totalChanges = modifiedCount + deletedCount
        let ratio: Double
        if totalFiles > 0 {
            ratio = Double(totalChanges) / Double(totalFiles)
        } else {
            ratio = 0.0
        }
        let changePercent = ratio * 100.0

        // 1. Detect known ransomware extensions
        var suspiciousFiles: [String] = []
        if detectSuspiciousExtensions {
            for path in candidatePaths {
                let lower = path.lowercased()
                for ext in knownSuspiciousExtensions {
                    if lower.hasSuffix(ext) {
                        suspiciousFiles.append(path)
                        break
                    }
                }
            }
        }

        if !suspiciousFiles.isEmpty {
            let sample = suspiciousFiles.prefix(3).joined(separator: ", ")
            let reason = "Suspicious ransomware extensions detected (\(suspiciousFiles.count) files, e.g. [\(sample)])"
            return RansomwareAnomalyReport(
                isAnomalyDetected: true,
                modifiedRatio: ratio,
                modifiedCount: modifiedCount,
                deletedCount: deletedCount,
                totalSourceFiles: totalFiles,
                suspiciousExtensionFiles: suspiciousFiles,
                reason: reason
            )
        }

        // 2. Evaluate mass deletion threshold
        if maxDeletedThresholdCount > 0 && deletedCount >= maxDeletedThresholdCount {
            let reason = "Mass deletion anomaly: \(deletedCount) files deleted, exceeding safe threshold of \(maxDeletedThresholdCount)"
            return RansomwareAnomalyReport(
                isAnomalyDetected: true,
                modifiedRatio: ratio,
                modifiedCount: modifiedCount,
                deletedCount: deletedCount,
                totalSourceFiles: totalFiles,
                suspiciousExtensionFiles: [],
                reason: reason
            )
        }

        // 3. Evaluate rate-of-change percentage threshold (requires >= 10 total files and >= 5 changes to avoid false positives on small directories)
        if totalFiles >= 10 && totalChanges >= 5 && changePercent >= maxChangeThresholdPercent {
            let reason = "Rate of change anomaly: \(String(format: "%.1f", changePercent))% changed (\(totalChanges)/\(totalFiles) files), exceeding threshold of \(String(format: "%.1f", maxChangeThresholdPercent))%"
            return RansomwareAnomalyReport(
                isAnomalyDetected: true,
                modifiedRatio: ratio,
                modifiedCount: modifiedCount,
                deletedCount: deletedCount,
                totalSourceFiles: totalFiles,
                suspiciousExtensionFiles: [],
                reason: reason
            )
        }

        return RansomwareAnomalyReport(
            isAnomalyDetected: false,
            modifiedRatio: ratio,
            modifiedCount: modifiedCount,
            deletedCount: deletedCount,
            totalSourceFiles: totalFiles,
            suspiciousExtensionFiles: [],
            reason: nil
        )
    }

    /// Convenience evaluator using `BackupProfile` settings and `ChangeDetectionResult`.
    public static func evaluate(
        scannedItems: [ScannedItem],
        changes: ChangeDetectionResult,
        profile: BackupProfile
    ) -> RansomwareAnomalyReport {
        let totalFiles = max(scannedItems.count, changes.unmodified.count + changes.added.count + changes.modified.count)
        var candidatePaths: [String] = []
        candidatePaths.reserveCapacity(changes.added.count + changes.modified.count)

        for item in changes.added {
            candidatePaths.append(item.relativePath)
        }
        for item in changes.modified {
            candidatePaths.append(item.relativePath)
        }

        return evaluate(
            totalFiles: totalFiles,
            modifiedCount: changes.modified.count,
            deletedCount: changes.deleted.count,
            candidatePaths: candidatePaths,
            enableGuard: profile.enableRateOfChangeGuard,
            maxChangeThresholdPercent: profile.maxChangeThresholdPercent,
            maxDeletedThresholdCount: profile.maxDeletedThresholdCount,
            detectSuspiciousExtensions: profile.detectKnownRansomwareExtensions
        )
    }
}
